#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

# parse env items
while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_SM_ENV_) ]] ; then
    exportName=$(echo "${name}" | sed 's/^BUILDKITE_PLUGIN_AWS_SM_ENV_//')
    secretId=$(strip_quotes "${!name}")
    echo "--- :aws::key: Reading ${secretId} from AWS SM into environment variable ${exportName}"
    value=$(get_secret_value "${secretId}")
    export "${exportName}=${value}"
    outputVal=$(echo -n "${value}" | cut -c-6)
    echo "Exported ${exportName} with value of ${outputVal}"

  fi
done < <(env | sort)
